site_name: Unix Time Ends in 2038. I think we'll have it figured out by then

theme:
  name: mkdocs
#  palette:
#    primary: grey
#    accent: red
#  font:
#    text: Courier Prime
#  icon:
#    logo: images/favicon.png
  favicon: images/ithinkt.png
  features:
    - navigation.expand
